version: '3.8'

services:
  # --- BACKEND ---
  backend:
    build: ../backend
    container_name: disc_backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/v1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPA_URL=http://opa:8181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC_AUDIT=audit-logs
    # Command uses main:app (no relative dots here)
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - opa
      - kafka
    networks:
      - disc-network

  # --- INFRASTRUCTURE ---
  redis:
    image: redis:7-alpine
    container_name: disc_redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru --save "" --appendonly no
    networks:
      - disc-network

  opa:
    image: openpolicyagent/opa:latest
    container_name: disc_opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--diagnostic-addr=0.0.0.0:8282"
      - "/policies"
    volumes:
      - ./../policies:/policies
    networks:
      - disc-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: disc_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - disc-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: disc_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - disc-network

  frontend:
    build: ../frontend
    container_name: disc_frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8000/v1
    depends_on:
      - backend
    networks:
      - disc-network

networks:
  disc-network:
    driver: bridge